#!/bin/sh

set -e

echo "create group for dhis instances and group for dhis admins"
addgroup dhis2admin 2>/dev/null || { echo "dhis2admin group exists"; }
addgroup dhis2 2>/dev/null || { echo "dhis2 group exists"; }

# echo "apache module setup"
# a2enmod rewrite headers proxy_ajp disk_cache ssl

exit 0
