#!/bin/bash

git_commit_push () {
  echo "* Add all files and commit.."
  git add -A
  git commit -m "${1}"
  echo "* Push to remote.."
  git push
}

if [ $# -lt 1 ]; then
  echo -e "Usage:   $0 <commit-message>"
  echo -e "Example: $0 \"Add power boost\""
  exit 1
fi

git_commit_push $1
