#!/bin/bash

# Git command which will:
#
# * Add all files
# * Commit with the given message
# * Push to remote

git_commit_push () {
  echo "* Adding files.."
  git add -A
  echo "* Committing.."
  git commit -m "${1}"
  echo "* Pushing to remote.."
  git push
}

if [ $# -lt 1 ]; then
  echo -e "Usage:   $0 <commit-message>"
  echo -e "Example: $0 \"Add power boost\""
  exit 1
fi

git_commit_push $1
