
-- Function for terminating slow queries generated by DHIS 2

-- Adjust username filter as necessary, set to 'dhis' by default. For regular use, use `dhis_cancel_show_queries()` instead.

-- To invoke run $ select dhis_terminate_slow_queries();

drop function if exists dhis_terminate_slow_queries();

create function dhis_terminate_slow_queries()
returns integer as $$
declare
	q record;
	c integer := 0;
begin
	for q in select * from pg_catalog.pg_stat_activity where (now() - pg_stat_activity.query_start) > interval '2 minutes' and usename = 'dhis'
	loop
		raise notice 'Terminating query with PID: %', q.pid;
		perform pg_terminate_backend(q.pid);
		c := c + 1;
	end loop;
	return c;
end;
$$ language plpgsql;
