--
-- Queries for the pg_stat_statements PostgreSQL extension
--
-- Configuration changes require a PostgreSQL server restart to take effect
--
-- Enable 'pg_stat_statements' extension
--
-- Create new config file 'pg_stat_statements.conf' and put in 'conf.d' directory
--

-- -- BEGIN --

# pg_stat_statements

# Enable library
shared_preload_libraries = 'pg_stat_statements'

# Increase memory for recorded queries
track_activity_query_size = 8192

# Track statements generated by stored procedures
pg_stat_statements.track = 'all'

# Increse max statements to track
pg_stat_statements.max = 10000

-- -- END --

-- Create schema for extension

create schema if not exists stat;

-- Create extension for the specific database from psql CLI

create extension pg_stat_statements schema stat;

--
-- Use \x in psql for expanded display
--
-- Time unit is milliseconds
--

-- Create base view for statistics

drop view if exists stat.view_pg_stat_statements;

create view stat.view_pg_stat_statements as
select 
  to_char(mean_exec_time, 'FM999G999G999G990') as mean_time_ms,
  to_char((total_exec_time/calls), 'FM999G999G999G990') as avg_time_ms,
  to_char(max_exec_time, 'FM999G999G999G990') as max_time_ms,
  to_char(min_exec_time, 'FM999G999G999G990') as min_time_ms,
  to_char(total_exec_time, 'FM999G999G999G990') as total_time_ms,
  to_char(stddev_exec_time, 'FM999G999G990') as std_dev_time,
  calls, 
  rows,
  mean_exec_time, 
  total_exec_time,
  length(query) as query_length,
  substring(query, 0, 750) as query
from stat.pg_stat_statements
limit 200;

-- Create slow queries view

drop view if exists stat.view_slow_queries;

create view stat.view_slow_queries as
select 
  to_char(mean_exec_time, 'FM999G999G999G990') as mean_time_ms,
  to_char(max_exec_time, 'FM999G999G999G990') as max_time_ms,
  to_char(min_exec_time, 'FM999G999G999G990') as min_time_ms,
  query
from stat.pg_stat_statements
order by mean_exec_time desc
limit 200;

-- Create frequent queries view

drop view if exists stat.view_frequent_queries;

create view stat.view_frequent_queries as
select 
  to_char(mean_exec_time, 'FM999G999G999G990') as mean_time_ms,
  to_char(total_exec_time, 'FM999G999G999G990') as total_time_ms,
  calls, 
  rows,
  query
from stat.pg_stat_statements
order by total_exec_time desc
limit 200;

-- Slow queries ordered by mean time desc (time in ms)

select * from stat.view_slow_queries;

-- Frequent and time consuming queries ordered by total time desc (time in ms)

select * from stat.view_frequent_queries;
